apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    type: deployment
  name: busybox-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: busybox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
    spec:  

      containers:
      - name: init
        image: busybox:1.28
        command:
        - sh
        - -c
        - |
          echo "1. removing everything except conf file"
          find /init -mindepth 1 -maxdepth 1 -not -name 'conf' -exec rm -rf {} \;
          echo "2. downloading web page"
          wget -O /init/index.html www.stackoverflow.com
        volumeMounts:
        - mountPath: /init
          name: volume-shared #change

      volumes:
      - name: volume-shared
        persistentVolumeClaim:
          claimName: csi-s3-pvc