nameOverride: ""
fullnameOverride: ""

replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  monitoring:
    enabled: true
    name: monitoring
  cd:
    enabled: true
    name: cd

initContainer:
  name: init
  image: busybox
  tag: "1.28"
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: homework.otus
      paths:
        - path: /
          pathType: ImplementationSpecific
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

readinessProbe:
  enabled: true

storage:
  persistentVolumeClaim:
    enabled: true
    name: homework-pvc
    storage: 100Mi
    
  storageClass:
    enabled: true
    name: kb-class-storage
    provisioner: k8s.io/minikube-hostpath
    reclaimPolicy: Retain
    volumeBindingMode: Immediate

homework_cm:
  name: homework-cm
  

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: homework
          operator: In
          values: 
          - 'true'

redis:
  replica:
    replicaCount: 1