apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki-stack
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http-metrics
  - port: 9096
    targetPort: 9096
    protocol: TCP
    name: grpc
---
# Gateway service для совместимости с Helm чартом
apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: loki-stack
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
  - port: 80
    targetPort: 3100
    protocol: TCP
    name: http