apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.homework_cm.name }}
  namespace: {{ include "renapp.namespace" . }}
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen  {{ .Values.service.port }};
      root /homework;
      index index.html;
      location / {
        try_files $uri $uri/ /index.html;     
      }
      location /metrics {
        try_files $uri $uri/ /metrics.html;     
      }
    }
  homework-conf: |
    hello, I'am a configMap