apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-metrics-binding
  namespace: {{ include "renapp.namespace" . }}
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.monitoring.name }}
    namespace: {{ include "renapp.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ include "renapp.namespace" . }}
  name: cd-binding
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.cd.name }}
    namespace: {{ include "renapp.namespace" . }}