{{- if .Values.serviceAccount.monitoring.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.monitoring.name }}
  namespace: {{ include "renapp.namespace" . }}
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.serviceAccount.cd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.cd.name }}
  namespace: {{ include "renapp.namespace" . }}
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
{{- end }}