apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "renapp.namespace" . }}
  name: {{ include "renapp.fullname" . }}
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-web-pod
      protocol: TCP
      name: http-web-svc
  selector:
    {{- include "renapp.selectorLabels" . | nindent 4 }}
