apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    {{- include "renapp.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: EnsureExists
  name: {{ .Values.storage.storageClass.name }}
  namespace: {{ include "renapp.namespace" . }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode }}
