# helm-charts/values-loki.yaml
loki:
  auth_enabled: false
  
  storage:
    type: s3
    s3:
      endpoint: storage.yandexcloud.net:443
      region: ru-central1
      s3forcepathstyle: true
      insecure: false
  
  image:
    repository: grafana/loki
    tag: 2.9.8
    pullPolicy: IfNotPresent

  # Размещаем Loki только на infra нодах
  nodeSelector:
    node-role: infra
  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

promtail:
  enabled: true  # Включаем Promtail
  
  image:
    repository: grafana/promtail
    tag: 2.9.8
    pullPolicy: IfNotPresent
  
  # Promtail должен быть на ВСЕХ нодах для сбора логов
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  
  # Конфигурация Promtail
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    snippets:
      pipelineStages:
        - cri: {}
        - labeldrop:
          - filename
          - stream
    
    # Дополнительные scrape configs если нужно
    extraScrapeConfigs: |
      # Системные логи
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'

grafana:
  enabled: true
  
  image:
    repository: grafana/grafana
    tag: latest
  
  # Grafana тоже на infra нодах
  nodeSelector:
    node-role: infra
  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
  
  adminPassword: admin
  
  # Автоматически добавляем Loki как datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true