repositories:
  - name: bitnami
    url: https://mirror.yandex.ru/helm/charts.bitnami.com

releases:
  - name: kafka
    namespace: prod
    chart: bitnami/kafka
    version: 32.1.3
    values:
      - prod_values.yaml
  - name: kafka
    namespace: dev
    chart: bitnami/kafka
    version: 32.1.3
    values:
      - dev_values.yaml
